version: '3'

services:
    brevets:
        build: brevets/.
        ports: 
          - "5098:5000"
        environment: 
          MONGODB_HOSTNAME: brevetsdb
        depends_on:
          - brevetsdb
        volumes:
          - type: bind
            source: ./brevets
            target: /app
    brevetsdb:
        image: mongo:5.0.5
